# Neural Network

<img src="https://i.postimg.cc/5NKS0rfx/nn.png" alt="NN" width="500"/>

In [6]:
import numpy as np

class NeuralNetwork():

    # Set random seed
    np.random.seed(42)

    def __init__(self, X, y, n_hidden_neurons, output_act_fn = 'linear', error_fn = 'mse'):
        self.X = X
        self.y = y
        self.n_input_neurons = X.shape[1]
        self.n_hidden_neurons = n_hidden_neurons
        self.output_act_fn = output_act_fn
        self.error_fn = error_fn

        # Initialize weights and biases with random values (array of random numbers)
        self.input_hidden_weights = np.random.randn(self.n_input_neurons, self.n_hidden_neurons)
        self.hidden_biases = np.random.randn(self.n_hidden_neurons)
        self.hidden_output_weights = np.random.randn(self.n_hidden_neurons, 1)
        self.output_bias = np.random.randn(1)

    def activation(self, x, act_fn):
        if act_fn == 'sigmoid':
            return 1 / (1 + np.exp(-x))
        elif act_fn == 'relu':
            return np.maximum(0, x)
        elif act_fn == 'linear':
            return x
        else:
            raise Exception('Unknown activation function')

    def activation_derivative(self, x, act_fn):
        if act_fn == 'sigmoid':
            return x * (1 - x)
        elif act_fn == 'relu':
            return np.where(x > 0, 1, 0)
        elif act_fn == 'linear':
            return 1
        else:
            raise Exception('Unknown activation function')

    # Forward Propagation
    def forward_pass(self, X):
        # Input layer
        self.input = X

        # Hidden layer
        self.hidden = self.activation(np.dot(self.input, self.input_hidden_weights) + self.hidden_biases, 'relu')

        # Output layer
        self.output = self.activation(np.dot(self.hidden, self.hidden_output_weights) + self.output_bias, self.output_act_fn)

        return self.output

    # Error Estimation
    def error(self, y_true, y_pred):
        if self.error_fn == 'mse':
            return np.mean(np.square(y_true - y_pred))
        elif self.error_fn == 'cross_entropy':
            return -np.mean(y_true * np.log(y_pred+0.00001) + (1 - y_true) * np.log(1 - y_pred+0.00001))
        else:
            raise Exception('Unknown error function')

    def error_derivative(self, y_true, y_pred):
        if self.error_fn == 'mse':
            return  2 * (y_pred - y_true) / y_true.size
        elif self.error_fn == 'cross_entropy':
            return (y_pred - y_true) / (y_pred * (1 - y_pred+.00001) * y_true.size)
        else:
            raise Exception('Unknown error function')

    # Backpropagation
    def backward_pass(self, X, y_true, y_pred, learning_rate):
        # Output layer
        self.output_error = self.error_derivative(y_true, y_pred) * self.activation_derivative(y_pred, self.output_act_fn)
        self.output_bias -= learning_rate * np.sum(self.output_error, axis=0)
        self.hidden_output_weights -= learning_rate * np.dot(self.hidden.T, self.output_error)

        # Hidden layer
        self.hidden_error = np.dot(self.output_error, self.hidden_output_weights.T) * self.activation_derivative(self.hidden, 'relu')
        self.hidden_biases -= learning_rate * np.sum(self.hidden_error, axis=0)
        self.input_hidden_weights -= learning_rate * np.dot(X.T, self.hidden_error)

        # return weights and biases
        return self.input_hidden_weights, self.hidden_biases, self.hidden_output_weights, self.output_bias

    # Training
    def train(self, X, y, learning_rate, epochs):
        for epoch in range(epochs):
            y_pred = self.forward_pass(X)
            wih, bh, who, bo = self.backward_pass(X, y, y_pred, learning_rate)
            if epoch % 500 == 0:
                print('Epoch: {}, Loss: {:.3f}'.format(epoch, self.error(y, y_pred)))
        print('Training complete!')
        return wih, bh, who, bo

    # Prediction
    def predict(self, X):
        if self.error_fn == 'mse':
            return self.forward_pass(X)
        elif self.error_fn == 'cross_entropy':
            return np.where(self.forward_pass(X) > 0.5, 1, 0)


In [9]:
# Create dataset
X = np.random.rand(100, 2)  # 100 samples, 2 features
y = np.random.randint(0, 2, (100, 1))  # Binary labels (0 or 1)
y= y.reshape(-1,1)
# Initialize neural network
nn = NeuralNetwork(X, y, n_hidden_neurons=4, output_act_fn='sigmoid', error_fn='mse')

# Train the network
nn.train(X, y, learning_rate=0.01, epochs=5000)

# Make predictions
predictions = nn.predict(X)
print(predictions)


Epoch: 0, Loss: 0.276
Epoch: 500, Loss: 0.249
Epoch: 1000, Loss: 0.248
Epoch: 1500, Loss: 0.248
Epoch: 2000, Loss: 0.247
Epoch: 2500, Loss: 0.247
Epoch: 3000, Loss: 0.247
Epoch: 3500, Loss: 0.247
Epoch: 4000, Loss: 0.247
Epoch: 4500, Loss: 0.247
Training complete!
[[0.55314893]
 [0.55769776]
 [0.51367661]
 [0.56210396]
 [0.53213688]
 [0.60894962]
 [0.51834702]
 [0.56871805]
 [0.50131241]
 [0.46098408]
 [0.44747392]
 [0.59248428]
 [0.43322689]
 [0.59413441]
 [0.57398023]
 [0.41737241]
 [0.51008746]
 [0.52437114]
 [0.52843662]
 [0.59461739]
 [0.53394431]
 [0.38279075]
 [0.56654975]
 [0.51840824]
 [0.45828842]
 [0.50638875]
 [0.56434238]
 [0.58761799]
 [0.51474251]
 [0.51384278]
 [0.46346405]
 [0.43867727]
 [0.45040562]
 [0.56996401]
 [0.53998166]
 [0.51159251]
 [0.44880834]
 [0.48226634]
 [0.58029888]
 [0.47663022]
 [0.48680424]
 [0.57473047]
 [0.41350834]
 [0.40858658]
 [0.59847965]
 [0.4781912 ]
 [0.49958422]
 [0.61562134]
 [0.57733273]
 [0.48041486]
 [0.46397395]
 [0.41550071]
 [0.436

In [11]:
wih, bh, who, bo= nn.train(X, y, learning_rate=0.001, epochs=5000)

Epoch: 0, Loss: 0.247
Epoch: 500, Loss: 0.247
Epoch: 1000, Loss: 0.247
Epoch: 1500, Loss: 0.247
Epoch: 2000, Loss: 0.247
Epoch: 2500, Loss: 0.247
Epoch: 3000, Loss: 0.247
Epoch: 3500, Loss: 0.247
Epoch: 4000, Loss: 0.247
Epoch: 4500, Loss: 0.247
Training complete!


In [12]:
# Weights and biases
print('Input-hidden weights:\n', wih)
print('Hidden-output weights:\n', who)
print('Hidden biases:\n', bh)
print('Output bias:\n', bo)

Input-hidden weights:
 [[-0.94445665 -1.71313453  1.31957649 -0.11453985]
 [ 1.22762151 -1.59442766 -0.55970349  0.0052437 ]]
Hidden-output weights:
 [[0.0802182 ]
 [0.12029563]
 [0.67071636]
 [0.71161488]]
Hidden biases:
 [ 0.03226954 -0.45006547  0.84320078 -1.06762043]
Output bias:
 [-0.78891268]


# Regression Example

In [13]:
from sklearn.datasets import make_regression
X, y = make_regression(n_samples=1000, n_features=3, noise=20, random_state=42)
y = y.reshape(-1, 1)

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [14]:
nn = NeuralNetwork(X_train, y_train,  n_hidden_neurons=128, output_act_fn='linear', error_fn='mse')
wih, bh, who, bo= nn.train(X_train, y_train, learning_rate=0.001, epochs=5000)

Epoch: 0, Loss: 18004.477
Epoch: 500, Loss: 371.140
Epoch: 1000, Loss: 362.546
Epoch: 1500, Loss: 359.088
Epoch: 2000, Loss: 356.734
Epoch: 2500, Loss: 354.845
Epoch: 3000, Loss: 353.089
Epoch: 3500, Loss: 351.570
Epoch: 4000, Loss: 350.041
Epoch: 4500, Loss: 348.558
Training complete!


In [15]:
# Accuracy
from sklearn.metrics import r2_score
y_pred = nn.predict(X_test)
print('R2 Score: {:.3f}'.format(r2_score(y_test, y_pred)))

R2 Score: 0.975


In [16]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred = lr.predict(X_test)
print('R2 Score: {:.3f}'.format(r2_score(y_test, y_pred)))

R2 Score: 0.976
